# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.4.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if getattr(globals().get("__spec__"), "parent", None) or __package__ or "." in __name__:
    from . import _oecluster
else:
    import _oecluster

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _oecluster.delete_SwigPyIterator

    def value(self):
        return _oecluster.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _oecluster.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _oecluster.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _oecluster.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _oecluster.SwigPyIterator_equal(self, x)

    def copy(self):
        return _oecluster.SwigPyIterator_copy(self)

    def next(self):
        return _oecluster.SwigPyIterator_next(self)

    def __next__(self):
        return _oecluster.SwigPyIterator___next__(self)

    def previous(self):
        return _oecluster.SwigPyIterator_previous(self)

    def advance(self, n):
        return _oecluster.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _oecluster.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _oecluster.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _oecluster.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _oecluster.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _oecluster.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _oecluster.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _oecluster:
_oecluster.SwigPyIterator_swigregister(SwigPyIterator)
class StringVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _oecluster.StringVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _oecluster.StringVector___nonzero__(self)

    def __bool__(self):
        return _oecluster.StringVector___bool__(self)

    def __len__(self):
        return _oecluster.StringVector___len__(self)

    def __getslice__(self, i, j):
        return _oecluster.StringVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _oecluster.StringVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _oecluster.StringVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _oecluster.StringVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _oecluster.StringVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _oecluster.StringVector___setitem__(self, *args)

    def pop(self):
        return _oecluster.StringVector_pop(self)

    def append(self, x):
        return _oecluster.StringVector_append(self, x)

    def empty(self):
        return _oecluster.StringVector_empty(self)

    def size(self):
        return _oecluster.StringVector_size(self)

    def swap(self, v):
        return _oecluster.StringVector_swap(self, v)

    def begin(self):
        return _oecluster.StringVector_begin(self)

    def end(self):
        return _oecluster.StringVector_end(self)

    def rbegin(self):
        return _oecluster.StringVector_rbegin(self)

    def rend(self):
        return _oecluster.StringVector_rend(self)

    def clear(self):
        return _oecluster.StringVector_clear(self)

    def get_allocator(self):
        return _oecluster.StringVector_get_allocator(self)

    def pop_back(self):
        return _oecluster.StringVector_pop_back(self)

    def erase(self, *args):
        return _oecluster.StringVector_erase(self, *args)

    def __init__(self, *args):
        _oecluster.StringVector_swiginit(self, _oecluster.new_StringVector(*args))

    def push_back(self, x):
        return _oecluster.StringVector_push_back(self, x)

    def front(self):
        return _oecluster.StringVector_front(self)

    def back(self):
        return _oecluster.StringVector_back(self)

    def assign(self, n, x):
        return _oecluster.StringVector_assign(self, n, x)

    def resize(self, *args):
        return _oecluster.StringVector_resize(self, *args)

    def insert(self, *args):
        return _oecluster.StringVector_insert(self, *args)

    def reserve(self, n):
        return _oecluster.StringVector_reserve(self, n)

    def capacity(self):
        return _oecluster.StringVector_capacity(self)
    __swig_destroy__ = _oecluster.delete_StringVector

# Register StringVector in _oecluster:
_oecluster.StringVector_swigregister(StringVector)
class StorageBackend(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _oecluster.delete_StorageBackend

    def Set(self, i, j, value):
        return _oecluster.StorageBackend_Set(self, i, j, value)

    def Get(self, i, j):
        return _oecluster.StorageBackend_Get(self, i, j)

    def NumItems(self):
        return _oecluster.StorageBackend_NumItems(self)

    def NumPairs(self):
        return _oecluster.StorageBackend_NumPairs(self)

    def Finalize(self):
        return _oecluster.StorageBackend_Finalize(self)

    def _data_ptr(self):
        r"""Return raw data pointer as integer address for numpy interop."""
        return _oecluster.StorageBackend__data_ptr(self)

# Register StorageBackend in _oecluster:
_oecluster.StorageBackend_swigregister(StorageBackend)
class DenseStorage(StorageBackend):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, n):
        _oecluster.DenseStorage_swiginit(self, _oecluster.new_DenseStorage(n))

    def Set(self, i, j, value):
        return _oecluster.DenseStorage_Set(self, i, j, value)

    def Get(self, i, j):
        return _oecluster.DenseStorage_Get(self, i, j)

    def NumItems(self):
        return _oecluster.DenseStorage_NumItems(self)

    def NumPairs(self):
        return _oecluster.DenseStorage_NumPairs(self)
    __swig_destroy__ = _oecluster.delete_DenseStorage

# Register DenseStorage in _oecluster:
_oecluster.DenseStorage_swigregister(DenseStorage)
class MMapStorage(StorageBackend):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, path, n):
        _oecluster.MMapStorage_swiginit(self, _oecluster.new_MMapStorage(path, n))
    __swig_destroy__ = _oecluster.delete_MMapStorage

    def Set(self, i, j, value):
        return _oecluster.MMapStorage_Set(self, i, j, value)

    def Get(self, i, j):
        return _oecluster.MMapStorage_Get(self, i, j)

    def NumItems(self):
        return _oecluster.MMapStorage_NumItems(self)

    def NumPairs(self):
        return _oecluster.MMapStorage_NumPairs(self)

# Register MMapStorage in _oecluster:
_oecluster.MMapStorage_swigregister(MMapStorage)
class SparseStorage(StorageBackend):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, n, cutoff):
        _oecluster.SparseStorage_swiginit(self, _oecluster.new_SparseStorage(n, cutoff))
    __swig_destroy__ = _oecluster.delete_SparseStorage

    def Set(self, i, j, value):
        return _oecluster.SparseStorage_Set(self, i, j, value)

    def Get(self, i, j):
        return _oecluster.SparseStorage_Get(self, i, j)

    def NumItems(self):
        return _oecluster.SparseStorage_NumItems(self)

    def NumPairs(self):
        return _oecluster.SparseStorage_NumPairs(self)

    def Finalize(self):
        return _oecluster.SparseStorage_Finalize(self)

    def _entries(self):
        r"""Return entries as a Python list of (i, j, value) tuples."""
        return _oecluster.SparseStorage__entries(self)

# Register SparseStorage in _oecluster:
_oecluster.SparseStorage_swigregister(SparseStorage)
class OEClusterError(object):
    r"""Base exception for all OECluster errors."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _oecluster.delete_OEClusterError

# Register OEClusterError in _oecluster:
_oecluster.OEClusterError_swigregister(OEClusterError)
class MetricError(OEClusterError):
    r"""Exception for metric-related failures (Distance, Clone)."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _oecluster.delete_MetricError

# Register MetricError in _oecluster:
_oecluster.MetricError_swigregister(MetricError)
class StorageError(OEClusterError):
    r"""Exception for storage-related failures (MMap, file I/O)."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _oecluster.delete_StorageError

# Register StorageError in _oecluster:
_oecluster.StorageError_swigregister(StorageError)
class DistanceMetric(object):
    r"""
    Abstract base class for distance metrics.

    Defines the interface for computing pairwise distances between items.
    Implementations must be cloneable so that each thread in a parallel
    computation can own its own scorer objects, avoiding synchronization.
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _oecluster.delete_DistanceMetric

    def Distance(self, i, j):
        r"""
        Compute distance between items i and j.

        Must be thread-safe when called on a Clone()'d instance.

        :param i: Index of first item.
        :param j: Index of second item.
        :returns: Distance value between items i and j.
        """
        return _oecluster.DistanceMetric_Distance(self, i, j)

    def Size(self):
        r"""
        Number of items loaded into this metric.

        :returns: Number of items.
        """
        return _oecluster.DistanceMetric_Size(self)

    def Name(self):
        r"""
        Human-readable metric name.

        :returns: Name of the metric.
        """
        return _oecluster.DistanceMetric_Name(self)

# Register DistanceMetric in _oecluster:
_oecluster.DistanceMetric_swigregister(DistanceMetric)
class ThreadPool(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, num_threads=0):
        _oecluster.ThreadPool_swiginit(self, _oecluster.new_ThreadPool(num_threads))
    __swig_destroy__ = _oecluster.delete_ThreadPool

    def NumThreads(self):
        return _oecluster.ThreadPool_NumThreads(self)

    def Cancel(self):
        return _oecluster.ThreadPool_Cancel(self)

    def IsCancelled(self):
        return _oecluster.ThreadPool_IsCancelled(self)

# Register ThreadPool in _oecluster:
_oecluster.ThreadPool_swigregister(ThreadPool)
class PDistOptions(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    num_threads = property(_oecluster.PDistOptions_num_threads_get, _oecluster.PDistOptions_num_threads_set)
    chunk_size = property(_oecluster.PDistOptions_chunk_size_get, _oecluster.PDistOptions_chunk_size_set)
    cutoff = property(_oecluster.PDistOptions_cutoff_get, _oecluster.PDistOptions_cutoff_set)
    progress = property(_oecluster.PDistOptions_progress_get, _oecluster.PDistOptions_progress_set)

    def __init__(self):
        _oecluster.PDistOptions_swiginit(self, _oecluster.new_PDistOptions())
    __swig_destroy__ = _oecluster.delete_PDistOptions

# Register PDistOptions in _oecluster:
_oecluster.PDistOptions_swigregister(PDistOptions)

def pdist(*args):
    return _oecluster.pdist(*args)
class CDistOptions(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    num_threads = property(_oecluster.CDistOptions_num_threads_get, _oecluster.CDistOptions_num_threads_set)
    chunk_size = property(_oecluster.CDistOptions_chunk_size_get, _oecluster.CDistOptions_chunk_size_set)
    cutoff = property(_oecluster.CDistOptions_cutoff_get, _oecluster.CDistOptions_cutoff_set)
    progress = property(_oecluster.CDistOptions_progress_get, _oecluster.CDistOptions_progress_set)

    def __init__(self):
        _oecluster.CDistOptions_swiginit(self, _oecluster.new_CDistOptions())
    __swig_destroy__ = _oecluster.delete_CDistOptions

# Register CDistOptions in _oecluster:
_oecluster.CDistOptions_swigregister(CDistOptions)

def cdist(*args):
    return _oecluster.cdist(*args)
class DistanceMatrix(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def Storage(self):
        return _oecluster.DistanceMatrix_Storage(self)

    def MetricName(self):
        return _oecluster.DistanceMatrix_MetricName(self)

    def Labels(self):
        return _oecluster.DistanceMatrix_Labels(self)

    def NumItems(self):
        return _oecluster.DistanceMatrix_NumItems(self)

    def NumPairs(self):
        return _oecluster.DistanceMatrix_NumPairs(self)
    __swig_destroy__ = _oecluster.delete_DistanceMatrix

# Register DistanceMatrix in _oecluster:
_oecluster.DistanceMatrix_swigregister(DistanceMatrix)
class FingerprintOptions(object):
    r"""Configuration options for fingerprint generation."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    fp_type = property(_oecluster.FingerprintOptions_fp_type_get, _oecluster.FingerprintOptions_fp_type_set)
    numbits = property(_oecluster.FingerprintOptions_numbits_get, _oecluster.FingerprintOptions_numbits_set)
    min_distance = property(_oecluster.FingerprintOptions_min_distance_get, _oecluster.FingerprintOptions_min_distance_set)
    max_distance = property(_oecluster.FingerprintOptions_max_distance_get, _oecluster.FingerprintOptions_max_distance_set)
    atom_type_mask = property(_oecluster.FingerprintOptions_atom_type_mask_get, _oecluster.FingerprintOptions_atom_type_mask_set, doc=r"""0 = use method default""")
    bond_type_mask = property(_oecluster.FingerprintOptions_bond_type_mask_get, _oecluster.FingerprintOptions_bond_type_mask_set, doc=r"""0 = use method default""")
    similarity_func = property(_oecluster.FingerprintOptions_similarity_func_get, _oecluster.FingerprintOptions_similarity_func_set, doc=r"""Similarity function name""")
    similarity = property(_oecluster.FingerprintOptions_similarity_get, _oecluster.FingerprintOptions_similarity_set, doc=r"""Return raw similarity instead of distance""")

    def __init__(self):
        _oecluster.FingerprintOptions_swiginit(self, _oecluster.new_FingerprintOptions())
    __swig_destroy__ = _oecluster.delete_FingerprintOptions

# Register FingerprintOptions in _oecluster:
_oecluster.FingerprintOptions_swigregister(FingerprintOptions)
class FingerprintMetric(DistanceMetric):
    r"""
    Fingerprint-based distance metric using OEGraphSim similarity functions.

    Computes all molecular fingerprints upfront during construction, then
    returns a distance value based on the configured similarity metric.
    The fingerprint data is immutable and shared across clones via
    ``std::shared_ptr``.
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""
        Construct a FingerprintMetric from a set of molecules.

        Generates fingerprints for every molecule in *mols* using the
        fingerprint type and parameters specified by *opts*.

        :param mols: Pointers to molecules (not owned).
        :param opts: Fingerprint options.
        :raises MetricError: If fingerprint generation fails for any molecule.
        """
        _oecluster.FingerprintMetric_swiginit(self, _oecluster.new_FingerprintMetric(*args))

    def Distance(self, i, j):
        return _oecluster.FingerprintMetric_Distance(self, i, j)

    def Size(self):
        return _oecluster.FingerprintMetric_Size(self)

    def Name(self):
        return _oecluster.FingerprintMetric_Name(self)
    __swig_destroy__ = _oecluster.delete_FingerprintMetric

# Register FingerprintMetric in _oecluster:
_oecluster.FingerprintMetric_swigregister(FingerprintMetric)
ROCSScoreType_ComboNorm = _oecluster.ROCSScoreType_ComboNorm
r"""TanimotoCombo normalized to [0,1]: distance = 1.0 - combo/2.0"""
ROCSScoreType_Combo = _oecluster.ROCSScoreType_Combo
r"""TanimotoCombo with range [0,2]: distance = 2.0 - combo"""
ROCSScoreType_Shape = _oecluster.ROCSScoreType_Shape
r"""Shape Tanimoto with range [0,1]: distance = 1.0 - shape"""
ROCSScoreType_Color = _oecluster.ROCSScoreType_Color
r"""Color Tanimoto with range [0,1]: distance = 1.0 - color"""
class ROCSOptions(object):
    r"""Configuration options for ROCS overlay scoring."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    score_type = property(_oecluster.ROCSOptions_score_type_get, _oecluster.ROCSOptions_score_type_set, doc=r"""Scoring method""")
    color_ff_type = property(_oecluster.ROCSOptions_color_ff_type_get, _oecluster.ROCSOptions_color_ff_type_set, doc=r"""OEColorFFType (1=ImplicitMillsDean)""")
    similarity = property(_oecluster.ROCSOptions_similarity_get, _oecluster.ROCSOptions_similarity_set, doc=r"""Return raw similarity instead of distance""")

    def __init__(self):
        _oecluster.ROCSOptions_swiginit(self, _oecluster.new_ROCSOptions())
    __swig_destroy__ = _oecluster.delete_ROCSOptions

# Register ROCSOptions in _oecluster:
_oecluster.ROCSOptions_swigregister(ROCSOptions)
class ROCSMetric(DistanceMetric):
    r"""
    ROCS-style shape/color overlay distance metric using OEShape.

    Stores shared references to molecules and uses ``OEOverlay`` to compute
    pairwise overlay scores. Distance computation depends on score_type:
      - ComboNorm: ``1.0 - TanimotoCombo/2.0`` (range [0,1])
      - Combo: ``2.0 - TanimotoCombo`` (range [0,2])
      - Shape: ``1.0 - ShapeTanimoto`` (range [0,1])
      - Color: ``1.0 - ColorTanimoto`` (range [0,1])

    Each Clone() creates a new ``OEOverlay`` instance so that Distance()
    can be called concurrently from different threads without locking.
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""
        Construct a ROCSMetric from a set of molecules.

        Molecules are stored by shared_ptr and shared across clones.
        Each molecule should have 3D coordinates for meaningful results.

        :param mols: Shared pointers to molecules.
        :param opts: Scoring options.
        """
        _oecluster.ROCSMetric_swiginit(self, _oecluster.new_ROCSMetric(*args))
    __swig_destroy__ = _oecluster.delete_ROCSMetric

    def Distance(self, i, j):
        return _oecluster.ROCSMetric_Distance(self, i, j)

    def Size(self):
        return _oecluster.ROCSMetric_Size(self)

    def Name(self):
        return _oecluster.ROCSMetric_Name(self)

# Register ROCSMetric in _oecluster:
_oecluster.ROCSMetric_swigregister(ROCSMetric)
SuperposeMethod_GlobalCarbonAlpha = _oecluster.SuperposeMethod_GlobalCarbonAlpha
r"""All matched alpha carbon atoms (default)"""
SuperposeMethod_Global = _oecluster.SuperposeMethod_Global
r"""Global superposition"""
SuperposeMethod_DDM = _oecluster.SuperposeMethod_DDM
r"""Distance Difference Matrix"""
SuperposeMethod_Weighted = _oecluster.SuperposeMethod_Weighted
r"""Weighted DDM"""
SuperposeMethod_SSE = _oecluster.SuperposeMethod_SSE
r"""Secondary Structure Elements (Tanimoto score)"""
SuperposeMethod_SiteHopper = _oecluster.SuperposeMethod_SiteHopper
r"""SiteHopper patch score"""
SuperposeScoreType_Auto = _oecluster.SuperposeScoreType_Auto
r"""Natural score for the method"""
SuperposeScoreType_RMSD = _oecluster.SuperposeScoreType_RMSD
r"""Root mean square deviation"""
SuperposeScoreType_Tanimoto = _oecluster.SuperposeScoreType_Tanimoto
r"""Tanimoto coefficient [0,1]"""
SuperposeScoreType_PatchScore = _oecluster.SuperposeScoreType_PatchScore
r"""SiteHopper patch score [0,4]"""
class SuperposeOptions(object):
    r"""Configuration options for protein superposition."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    method = property(_oecluster.SuperposeOptions_method_get, _oecluster.SuperposeOptions_method_set)
    score_type = property(_oecluster.SuperposeOptions_score_type_get, _oecluster.SuperposeOptions_score_type_set)
    similarity = property(_oecluster.SuperposeOptions_similarity_get, _oecluster.SuperposeOptions_similarity_set)
    predicate = property(_oecluster.SuperposeOptions_predicate_get, _oecluster.SuperposeOptions_predicate_set, doc=r"""oeselect expression for both ref and fit""")
    ref_predicate = property(_oecluster.SuperposeOptions_ref_predicate_get, _oecluster.SuperposeOptions_ref_predicate_set, doc=r"""Override predicate for ref""")
    fit_predicate = property(_oecluster.SuperposeOptions_fit_predicate_get, _oecluster.SuperposeOptions_fit_predicate_set, doc=r"""Override predicate for fit""")

    def __init__(self):
        _oecluster.SuperposeOptions_swiginit(self, _oecluster.new_SuperposeOptions())
    __swig_destroy__ = _oecluster.delete_SuperposeOptions

# Register SuperposeOptions in _oecluster:
_oecluster.SuperposeOptions_swigregister(SuperposeOptions)
class SuperposeMetric(DistanceMetric):
    r"""
    Protein superposition distance metric using oespruce OESuperpose.

    Supports multiple superposition methods (GlobalCarbonAlpha, Global, DDM,
    Weighted, SSE, SiteHopper) with configurable score types and atom predicates
    via oeselect expressions.

    Score semantics per method:
    - RMSD group (Global, GlobalCarbonAlpha, DDM, Weighted): raw RMSD
    - Tanimoto group (SSE): 1.0 - tanimoto (distance), raw tanimoto (similarity)
    - PatchScore group (SiteHopper): 4.0 - patch_score (distance), raw (similarity)

    Each Clone() creates a new thread-local OESuperpose instance.
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""
        *Overload 1:*

        Construct from design units.

        :param dus: Shared pointers to design units.
        :param opts: Superposition options.

        |

        *Overload 2:*

        Construct from molecules directly.

        Molecules are copied internally.

        :param mols: Pointers to molecules with 3D coordinates.
        :param opts: Superposition options.

        |

        *Overload 3:*

        Construct from molecules directly.

        Molecules are copied internally.

        :param mols: Pointers to molecules with 3D coordinates.
        :param opts: Superposition options.
        """
        _oecluster.SuperposeMetric_swiginit(self, _oecluster.new_SuperposeMetric(*args))
    __swig_destroy__ = _oecluster.delete_SuperposeMetric

    def Distance(self, i, j):
        return _oecluster.SuperposeMetric_Distance(self, i, j)

    def Size(self):
        return _oecluster.SuperposeMetric_Size(self)

    def Name(self):
        return _oecluster.SuperposeMetric_Name(self)

# Register SuperposeMetric in _oecluster:
_oecluster.SuperposeMetric_swigregister(SuperposeMetric)

