# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.4.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if getattr(globals().get("__spec__"), "parent", None) or __package__ or "." in __name__:
    from . import _oecluster
else:
    import _oecluster

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _oecluster.delete_SwigPyIterator

    def value(self):
        return _oecluster.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _oecluster.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _oecluster.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _oecluster.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _oecluster.SwigPyIterator_equal(self, x)

    def copy(self):
        return _oecluster.SwigPyIterator_copy(self)

    def next(self):
        return _oecluster.SwigPyIterator_next(self)

    def __next__(self):
        return _oecluster.SwigPyIterator___next__(self)

    def previous(self):
        return _oecluster.SwigPyIterator_previous(self)

    def advance(self, n):
        return _oecluster.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _oecluster.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _oecluster.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _oecluster.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _oecluster.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _oecluster.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _oecluster.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _oecluster:
_oecluster.SwigPyIterator_swigregister(SwigPyIterator)
class StringVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _oecluster.StringVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _oecluster.StringVector___nonzero__(self)

    def __bool__(self):
        return _oecluster.StringVector___bool__(self)

    def __len__(self):
        return _oecluster.StringVector___len__(self)

    def __getslice__(self, i, j):
        return _oecluster.StringVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _oecluster.StringVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _oecluster.StringVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _oecluster.StringVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _oecluster.StringVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _oecluster.StringVector___setitem__(self, *args)

    def pop(self):
        return _oecluster.StringVector_pop(self)

    def append(self, x):
        return _oecluster.StringVector_append(self, x)

    def empty(self):
        return _oecluster.StringVector_empty(self)

    def size(self):
        return _oecluster.StringVector_size(self)

    def swap(self, v):
        return _oecluster.StringVector_swap(self, v)

    def begin(self):
        return _oecluster.StringVector_begin(self)

    def end(self):
        return _oecluster.StringVector_end(self)

    def rbegin(self):
        return _oecluster.StringVector_rbegin(self)

    def rend(self):
        return _oecluster.StringVector_rend(self)

    def clear(self):
        return _oecluster.StringVector_clear(self)

    def get_allocator(self):
        return _oecluster.StringVector_get_allocator(self)

    def pop_back(self):
        return _oecluster.StringVector_pop_back(self)

    def erase(self, *args):
        return _oecluster.StringVector_erase(self, *args)

    def __init__(self, *args):
        _oecluster.StringVector_swiginit(self, _oecluster.new_StringVector(*args))

    def push_back(self, x):
        return _oecluster.StringVector_push_back(self, x)

    def front(self):
        return _oecluster.StringVector_front(self)

    def back(self):
        return _oecluster.StringVector_back(self)

    def assign(self, n, x):
        return _oecluster.StringVector_assign(self, n, x)

    def resize(self, *args):
        return _oecluster.StringVector_resize(self, *args)

    def insert(self, *args):
        return _oecluster.StringVector_insert(self, *args)

    def reserve(self, n):
        return _oecluster.StringVector_reserve(self, n)

    def capacity(self):
        return _oecluster.StringVector_capacity(self)
    __swig_destroy__ = _oecluster.delete_StringVector

# Register StringVector in _oecluster:
_oecluster.StringVector_swigregister(StringVector)
class SizeTVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _oecluster.SizeTVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _oecluster.SizeTVector___nonzero__(self)

    def __bool__(self):
        return _oecluster.SizeTVector___bool__(self)

    def __len__(self):
        return _oecluster.SizeTVector___len__(self)

    def __getslice__(self, i, j):
        return _oecluster.SizeTVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _oecluster.SizeTVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _oecluster.SizeTVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _oecluster.SizeTVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _oecluster.SizeTVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _oecluster.SizeTVector___setitem__(self, *args)

    def pop(self):
        return _oecluster.SizeTVector_pop(self)

    def append(self, x):
        return _oecluster.SizeTVector_append(self, x)

    def empty(self):
        return _oecluster.SizeTVector_empty(self)

    def size(self):
        return _oecluster.SizeTVector_size(self)

    def swap(self, v):
        return _oecluster.SizeTVector_swap(self, v)

    def begin(self):
        return _oecluster.SizeTVector_begin(self)

    def end(self):
        return _oecluster.SizeTVector_end(self)

    def rbegin(self):
        return _oecluster.SizeTVector_rbegin(self)

    def rend(self):
        return _oecluster.SizeTVector_rend(self)

    def clear(self):
        return _oecluster.SizeTVector_clear(self)

    def get_allocator(self):
        return _oecluster.SizeTVector_get_allocator(self)

    def pop_back(self):
        return _oecluster.SizeTVector_pop_back(self)

    def erase(self, *args):
        return _oecluster.SizeTVector_erase(self, *args)

    def __init__(self, *args):
        _oecluster.SizeTVector_swiginit(self, _oecluster.new_SizeTVector(*args))

    def push_back(self, x):
        return _oecluster.SizeTVector_push_back(self, x)

    def front(self):
        return _oecluster.SizeTVector_front(self)

    def back(self):
        return _oecluster.SizeTVector_back(self)

    def assign(self, n, x):
        return _oecluster.SizeTVector_assign(self, n, x)

    def resize(self, *args):
        return _oecluster.SizeTVector_resize(self, *args)

    def insert(self, *args):
        return _oecluster.SizeTVector_insert(self, *args)

    def reserve(self, n):
        return _oecluster.SizeTVector_reserve(self, n)

    def capacity(self):
        return _oecluster.SizeTVector_capacity(self)
    __swig_destroy__ = _oecluster.delete_SizeTVector

# Register SizeTVector in _oecluster:
_oecluster.SizeTVector_swigregister(SizeTVector)
class IntVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _oecluster.IntVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _oecluster.IntVector___nonzero__(self)

    def __bool__(self):
        return _oecluster.IntVector___bool__(self)

    def __len__(self):
        return _oecluster.IntVector___len__(self)

    def __getslice__(self, i, j):
        return _oecluster.IntVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _oecluster.IntVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _oecluster.IntVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _oecluster.IntVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _oecluster.IntVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _oecluster.IntVector___setitem__(self, *args)

    def pop(self):
        return _oecluster.IntVector_pop(self)

    def append(self, x):
        return _oecluster.IntVector_append(self, x)

    def empty(self):
        return _oecluster.IntVector_empty(self)

    def size(self):
        return _oecluster.IntVector_size(self)

    def swap(self, v):
        return _oecluster.IntVector_swap(self, v)

    def begin(self):
        return _oecluster.IntVector_begin(self)

    def end(self):
        return _oecluster.IntVector_end(self)

    def rbegin(self):
        return _oecluster.IntVector_rbegin(self)

    def rend(self):
        return _oecluster.IntVector_rend(self)

    def clear(self):
        return _oecluster.IntVector_clear(self)

    def get_allocator(self):
        return _oecluster.IntVector_get_allocator(self)

    def pop_back(self):
        return _oecluster.IntVector_pop_back(self)

    def erase(self, *args):
        return _oecluster.IntVector_erase(self, *args)

    def __init__(self, *args):
        _oecluster.IntVector_swiginit(self, _oecluster.new_IntVector(*args))

    def push_back(self, x):
        return _oecluster.IntVector_push_back(self, x)

    def front(self):
        return _oecluster.IntVector_front(self)

    def back(self):
        return _oecluster.IntVector_back(self)

    def assign(self, n, x):
        return _oecluster.IntVector_assign(self, n, x)

    def resize(self, *args):
        return _oecluster.IntVector_resize(self, *args)

    def insert(self, *args):
        return _oecluster.IntVector_insert(self, *args)

    def reserve(self, n):
        return _oecluster.IntVector_reserve(self, n)

    def capacity(self):
        return _oecluster.IntVector_capacity(self)
    __swig_destroy__ = _oecluster.delete_IntVector

# Register IntVector in _oecluster:
_oecluster.IntVector_swigregister(IntVector)
class DoubleVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _oecluster.DoubleVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _oecluster.DoubleVector___nonzero__(self)

    def __bool__(self):
        return _oecluster.DoubleVector___bool__(self)

    def __len__(self):
        return _oecluster.DoubleVector___len__(self)

    def __getslice__(self, i, j):
        return _oecluster.DoubleVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _oecluster.DoubleVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _oecluster.DoubleVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _oecluster.DoubleVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _oecluster.DoubleVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _oecluster.DoubleVector___setitem__(self, *args)

    def pop(self):
        return _oecluster.DoubleVector_pop(self)

    def append(self, x):
        return _oecluster.DoubleVector_append(self, x)

    def empty(self):
        return _oecluster.DoubleVector_empty(self)

    def size(self):
        return _oecluster.DoubleVector_size(self)

    def swap(self, v):
        return _oecluster.DoubleVector_swap(self, v)

    def begin(self):
        return _oecluster.DoubleVector_begin(self)

    def end(self):
        return _oecluster.DoubleVector_end(self)

    def rbegin(self):
        return _oecluster.DoubleVector_rbegin(self)

    def rend(self):
        return _oecluster.DoubleVector_rend(self)

    def clear(self):
        return _oecluster.DoubleVector_clear(self)

    def get_allocator(self):
        return _oecluster.DoubleVector_get_allocator(self)

    def pop_back(self):
        return _oecluster.DoubleVector_pop_back(self)

    def erase(self, *args):
        return _oecluster.DoubleVector_erase(self, *args)

    def __init__(self, *args):
        _oecluster.DoubleVector_swiginit(self, _oecluster.new_DoubleVector(*args))

    def push_back(self, x):
        return _oecluster.DoubleVector_push_back(self, x)

    def front(self):
        return _oecluster.DoubleVector_front(self)

    def back(self):
        return _oecluster.DoubleVector_back(self)

    def assign(self, n, x):
        return _oecluster.DoubleVector_assign(self, n, x)

    def resize(self, *args):
        return _oecluster.DoubleVector_resize(self, *args)

    def insert(self, *args):
        return _oecluster.DoubleVector_insert(self, *args)

    def reserve(self, n):
        return _oecluster.DoubleVector_reserve(self, n)

    def capacity(self):
        return _oecluster.DoubleVector_capacity(self)
    __swig_destroy__ = _oecluster.delete_DoubleVector

# Register DoubleVector in _oecluster:
_oecluster.DoubleVector_swigregister(DoubleVector)
class ClusterVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _oecluster.ClusterVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _oecluster.ClusterVector___nonzero__(self)

    def __bool__(self):
        return _oecluster.ClusterVector___bool__(self)

    def __len__(self):
        return _oecluster.ClusterVector___len__(self)

    def __getslice__(self, i, j):
        return _oecluster.ClusterVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _oecluster.ClusterVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _oecluster.ClusterVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _oecluster.ClusterVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _oecluster.ClusterVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _oecluster.ClusterVector___setitem__(self, *args)

    def pop(self):
        return _oecluster.ClusterVector_pop(self)

    def append(self, x):
        return _oecluster.ClusterVector_append(self, x)

    def empty(self):
        return _oecluster.ClusterVector_empty(self)

    def size(self):
        return _oecluster.ClusterVector_size(self)

    def swap(self, v):
        return _oecluster.ClusterVector_swap(self, v)

    def begin(self):
        return _oecluster.ClusterVector_begin(self)

    def end(self):
        return _oecluster.ClusterVector_end(self)

    def rbegin(self):
        return _oecluster.ClusterVector_rbegin(self)

    def rend(self):
        return _oecluster.ClusterVector_rend(self)

    def clear(self):
        return _oecluster.ClusterVector_clear(self)

    def get_allocator(self):
        return _oecluster.ClusterVector_get_allocator(self)

    def pop_back(self):
        return _oecluster.ClusterVector_pop_back(self)

    def erase(self, *args):
        return _oecluster.ClusterVector_erase(self, *args)

    def __init__(self, *args):
        _oecluster.ClusterVector_swiginit(self, _oecluster.new_ClusterVector(*args))

    def push_back(self, x):
        return _oecluster.ClusterVector_push_back(self, x)

    def front(self):
        return _oecluster.ClusterVector_front(self)

    def back(self):
        return _oecluster.ClusterVector_back(self)

    def assign(self, n, x):
        return _oecluster.ClusterVector_assign(self, n, x)

    def resize(self, *args):
        return _oecluster.ClusterVector_resize(self, *args)

    def insert(self, *args):
        return _oecluster.ClusterVector_insert(self, *args)

    def reserve(self, n):
        return _oecluster.ClusterVector_reserve(self, n)

    def capacity(self):
        return _oecluster.ClusterVector_capacity(self)
    __swig_destroy__ = _oecluster.delete_ClusterVector

# Register ClusterVector in _oecluster:
_oecluster.ClusterVector_swigregister(ClusterVector)
class StorageBackend(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _oecluster.delete_StorageBackend

    def Set(self, i, j, value):
        return _oecluster.StorageBackend_Set(self, i, j, value)

    def Get(self, i, j):
        return _oecluster.StorageBackend_Get(self, i, j)

    def NumItems(self):
        return _oecluster.StorageBackend_NumItems(self)

    def NumPairs(self):
        return _oecluster.StorageBackend_NumPairs(self)

    def Finalize(self):
        return _oecluster.StorageBackend_Finalize(self)

    def _data_ptr(self):
        r"""Return raw data pointer as integer address for numpy interop."""
        return _oecluster.StorageBackend__data_ptr(self)

# Register StorageBackend in _oecluster:
_oecluster.StorageBackend_swigregister(StorageBackend)
class DenseStorage(StorageBackend):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, n):
        _oecluster.DenseStorage_swiginit(self, _oecluster.new_DenseStorage(n))

    def Set(self, i, j, value):
        return _oecluster.DenseStorage_Set(self, i, j, value)

    def Get(self, i, j):
        return _oecluster.DenseStorage_Get(self, i, j)

    def NumItems(self):
        return _oecluster.DenseStorage_NumItems(self)

    def NumPairs(self):
        return _oecluster.DenseStorage_NumPairs(self)
    __swig_destroy__ = _oecluster.delete_DenseStorage

# Register DenseStorage in _oecluster:
_oecluster.DenseStorage_swigregister(DenseStorage)
class MMapStorage(StorageBackend):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, path, n):
        _oecluster.MMapStorage_swiginit(self, _oecluster.new_MMapStorage(path, n))
    __swig_destroy__ = _oecluster.delete_MMapStorage

    def Set(self, i, j, value):
        return _oecluster.MMapStorage_Set(self, i, j, value)

    def Get(self, i, j):
        return _oecluster.MMapStorage_Get(self, i, j)

    def NumItems(self):
        return _oecluster.MMapStorage_NumItems(self)

    def NumPairs(self):
        return _oecluster.MMapStorage_NumPairs(self)

# Register MMapStorage in _oecluster:
_oecluster.MMapStorage_swigregister(MMapStorage)
class SparseStorage(StorageBackend):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, n, cutoff):
        _oecluster.SparseStorage_swiginit(self, _oecluster.new_SparseStorage(n, cutoff))
    __swig_destroy__ = _oecluster.delete_SparseStorage

    def Set(self, i, j, value):
        return _oecluster.SparseStorage_Set(self, i, j, value)

    def Get(self, i, j):
        return _oecluster.SparseStorage_Get(self, i, j)

    def NumItems(self):
        return _oecluster.SparseStorage_NumItems(self)

    def NumPairs(self):
        return _oecluster.SparseStorage_NumPairs(self)

    def Finalize(self):
        return _oecluster.SparseStorage_Finalize(self)

    def _entries(self):
        r"""Return entries as a Python list of (i, j, value) tuples."""
        return _oecluster.SparseStorage__entries(self)

# Register SparseStorage in _oecluster:
_oecluster.SparseStorage_swigregister(SparseStorage)
class OEClusterError(object):
    r"""Base exception for all OECluster errors."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _oecluster.delete_OEClusterError

# Register OEClusterError in _oecluster:
_oecluster.OEClusterError_swigregister(OEClusterError)
class ComparisonError(OEClusterError):
    r"""Exception for comparison-related failures (Compare, Clone)."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _oecluster.delete_ComparisonError

# Register ComparisonError in _oecluster:
_oecluster.ComparisonError_swigregister(ComparisonError)
class StorageError(OEClusterError):
    r"""Exception for storage-related failures (MMap, file I/O)."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _oecluster.delete_StorageError

# Register StorageError in _oecluster:
_oecluster.StorageError_swigregister(StorageError)
class PairwiseComparison(object):
    r"""
    Abstract base class for pairwise comparison methods.

    Implementations own the data and scorer state needed to compare indexed
    items. They must be cloneable so each worker thread can evaluate pairs
    without synchronizing scorer internals.
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _oecluster.delete_PairwiseComparison

    def Compare(self, i, j):
        r"""
        Compare items i and j.

        The returned scalar follows the comparison's configured output mode,
        usually distance or similarity.

        :param i: Index of first item.
        :param j: Index of second item.
        :returns: Comparison value between items i and j.
        """
        return _oecluster.PairwiseComparison_Compare(self, i, j)

    def Size(self):
        r"""
        Number of items loaded into this comparison.

        :returns: Number of items.
        """
        return _oecluster.PairwiseComparison_Size(self)

    def ComparisonName(self):
        r"""
        Human-readable comparison name.

        :returns: Name of the comparison.
        """
        return _oecluster.PairwiseComparison_ComparisonName(self)

# Register PairwiseComparison in _oecluster:
_oecluster.PairwiseComparison_swigregister(PairwiseComparison)
class ThreadPool(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, num_threads=0):
        _oecluster.ThreadPool_swiginit(self, _oecluster.new_ThreadPool(num_threads))
    __swig_destroy__ = _oecluster.delete_ThreadPool

    def NumThreads(self):
        return _oecluster.ThreadPool_NumThreads(self)

    def Cancel(self):
        return _oecluster.ThreadPool_Cancel(self)

    def IsCancelled(self):
        return _oecluster.ThreadPool_IsCancelled(self)

# Register ThreadPool in _oecluster:
_oecluster.ThreadPool_swigregister(ThreadPool)
class PDistOptions(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    num_threads = property(_oecluster.PDistOptions_num_threads_get, _oecluster.PDistOptions_num_threads_set)
    chunk_size = property(_oecluster.PDistOptions_chunk_size_get, _oecluster.PDistOptions_chunk_size_set)
    cutoff = property(_oecluster.PDistOptions_cutoff_get, _oecluster.PDistOptions_cutoff_set)
    progress = property(_oecluster.PDistOptions_progress_get, _oecluster.PDistOptions_progress_set)

    def __init__(self):
        _oecluster.PDistOptions_swiginit(self, _oecluster.new_PDistOptions())
    __swig_destroy__ = _oecluster.delete_PDistOptions

# Register PDistOptions in _oecluster:
_oecluster.PDistOptions_swigregister(PDistOptions)

def pdist(*args):
    return _oecluster.pdist(*args)
class CDistOptions(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    num_threads = property(_oecluster.CDistOptions_num_threads_get, _oecluster.CDistOptions_num_threads_set)
    chunk_size = property(_oecluster.CDistOptions_chunk_size_get, _oecluster.CDistOptions_chunk_size_set)
    cutoff = property(_oecluster.CDistOptions_cutoff_get, _oecluster.CDistOptions_cutoff_set)
    progress = property(_oecluster.CDistOptions_progress_get, _oecluster.CDistOptions_progress_set)

    def __init__(self):
        _oecluster.CDistOptions_swiginit(self, _oecluster.new_CDistOptions())
    __swig_destroy__ = _oecluster.delete_CDistOptions

# Register CDistOptions in _oecluster:
_oecluster.CDistOptions_swigregister(CDistOptions)

def cdist(*args):
    return _oecluster.cdist(*args)
class DistanceMatrix(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def Storage(self):
        return _oecluster.DistanceMatrix_Storage(self)

    def ComparisonName(self):
        return _oecluster.DistanceMatrix_ComparisonName(self)

    def Labels(self):
        return _oecluster.DistanceMatrix_Labels(self)

    def NumItems(self):
        return _oecluster.DistanceMatrix_NumItems(self)

    def NumPairs(self):
        return _oecluster.DistanceMatrix_NumPairs(self)
    __swig_destroy__ = _oecluster.delete_DistanceMatrix

# Register DistanceMatrix in _oecluster:
_oecluster.DistanceMatrix_swigregister(DistanceMatrix)
class FingerprintOptions(object):
    r"""Configuration options for fingerprint generation."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    fp_type = property(_oecluster.FingerprintOptions_fp_type_get, _oecluster.FingerprintOptions_fp_type_set)
    numbits = property(_oecluster.FingerprintOptions_numbits_get, _oecluster.FingerprintOptions_numbits_set)
    min_distance = property(_oecluster.FingerprintOptions_min_distance_get, _oecluster.FingerprintOptions_min_distance_set)
    max_distance = property(_oecluster.FingerprintOptions_max_distance_get, _oecluster.FingerprintOptions_max_distance_set)
    metric = property(_oecluster.FingerprintOptions_metric_get, _oecluster.FingerprintOptions_metric_set, doc=r"""OEFP scalar metric name.""")
    similarity = property(_oecluster.FingerprintOptions_similarity_get, _oecluster.FingerprintOptions_similarity_set, doc=r"""Return raw similarity instead of distance""")

    def __init__(self):
        _oecluster.FingerprintOptions_swiginit(self, _oecluster.new_FingerprintOptions())
    __swig_destroy__ = _oecluster.delete_FingerprintOptions

# Register FingerprintOptions in _oecluster:
_oecluster.FingerprintOptions_swigregister(FingerprintOptions)
class FingerprintComparison(PairwiseComparison):
    r"""
    Fingerprint-based pairwise comparison using OEFP fingerprints.

    Computes all molecular fingerprints upfront during construction, then
    delegates scalar and batch comparisons to OEFP. The fingerprint data is
    immutable and shared across clones via ``std::shared_ptr``.
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""
        Construct a FingerprintComparison from a set of molecules.

        Generates fingerprints for every molecule in *mols* using the
        fingerprint type and parameters specified by *opts*.

        :param mols: Pointers to molecules (not owned).
        :param opts: Fingerprint options.
        :raises ComparisonError: If fingerprint generation fails for any molecule.
        """
        _oecluster.FingerprintComparison_swiginit(self, _oecluster.new_FingerprintComparison(*args))

    def Compare(self, i, j):
        return _oecluster.FingerprintComparison_Compare(self, i, j)

    def Size(self):
        return _oecluster.FingerprintComparison_Size(self)

    def ComparisonName(self):
        return _oecluster.FingerprintComparison_ComparisonName(self)
    __swig_destroy__ = _oecluster.delete_FingerprintComparison

# Register FingerprintComparison in _oecluster:
_oecluster.FingerprintComparison_swigregister(FingerprintComparison)
ROCSScoreType_ComboNorm = _oecluster.ROCSScoreType_ComboNorm
r"""TanimotoCombo normalized to [0,1]: distance = 1.0 - combo/2.0"""
ROCSScoreType_Combo = _oecluster.ROCSScoreType_Combo
r"""TanimotoCombo with range [0,2]: distance = 2.0 - combo"""
ROCSScoreType_Shape = _oecluster.ROCSScoreType_Shape
r"""Shape Tanimoto with range [0,1]: distance = 1.0 - shape"""
ROCSScoreType_Color = _oecluster.ROCSScoreType_Color
r"""Color Tanimoto with range [0,1]: distance = 1.0 - color"""
class ROCSOptions(object):
    r"""Configuration options for ROCS overlay scoring."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    score_type = property(_oecluster.ROCSOptions_score_type_get, _oecluster.ROCSOptions_score_type_set, doc=r"""Scoring method""")
    color_ff_type = property(_oecluster.ROCSOptions_color_ff_type_get, _oecluster.ROCSOptions_color_ff_type_set, doc=r"""OEColorFFType (1=ImplicitMillsDean)""")
    similarity = property(_oecluster.ROCSOptions_similarity_get, _oecluster.ROCSOptions_similarity_set, doc=r"""Return raw similarity instead of distance""")

    def __init__(self):
        _oecluster.ROCSOptions_swiginit(self, _oecluster.new_ROCSOptions())
    __swig_destroy__ = _oecluster.delete_ROCSOptions

# Register ROCSOptions in _oecluster:
_oecluster.ROCSOptions_swigregister(ROCSOptions)
class ROCSComparison(PairwiseComparison):
    r"""
    ROCS-style shape/color pairwise comparison using OEShape.

    Stores shared references to molecules and uses ``OEOverlay`` to compute
    pairwise overlay scores. Comparison output depends on score_type and mode:
      - ComboNorm: ``1.0 - TanimotoCombo/2.0`` (range [0,1])
      - Combo: ``2.0 - TanimotoCombo`` (range [0,2])
      - Shape: ``1.0 - ShapeTanimoto`` (range [0,1])
      - Color: ``1.0 - ColorTanimoto`` (range [0,1])

    Each Clone() creates a new ``OEOverlay`` instance so that Compare()
    can be called concurrently from different threads without locking.
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""
        Construct a ROCSComparison from a set of molecules.

        Molecules are stored by shared_ptr and shared across clones.
        Each molecule should have 3D coordinates for meaningful results.

        :param mols: Shared pointers to molecules.
        :param opts: Scoring options.
        """
        _oecluster.ROCSComparison_swiginit(self, _oecluster.new_ROCSComparison(*args))
    __swig_destroy__ = _oecluster.delete_ROCSComparison

    def Compare(self, i, j):
        return _oecluster.ROCSComparison_Compare(self, i, j)

    def Size(self):
        return _oecluster.ROCSComparison_Size(self)

    def ComparisonName(self):
        return _oecluster.ROCSComparison_ComparisonName(self)

# Register ROCSComparison in _oecluster:
_oecluster.ROCSComparison_swigregister(ROCSComparison)
SuperposeMethod_GlobalCarbonAlpha = _oecluster.SuperposeMethod_GlobalCarbonAlpha
r"""All matched alpha carbon atoms (default)"""
SuperposeMethod_Global = _oecluster.SuperposeMethod_Global
r"""Global superposition"""
SuperposeMethod_DDM = _oecluster.SuperposeMethod_DDM
r"""Distance Difference Matrix"""
SuperposeMethod_Weighted = _oecluster.SuperposeMethod_Weighted
r"""Weighted DDM"""
SuperposeMethod_SSE = _oecluster.SuperposeMethod_SSE
r"""Secondary Structure Elements (Tanimoto score)"""
SuperposeMethod_SiteHopper = _oecluster.SuperposeMethod_SiteHopper
r"""SiteHopper patch score"""
SuperposeScoreType_Auto = _oecluster.SuperposeScoreType_Auto
r"""Natural score for the method"""
SuperposeScoreType_RMSD = _oecluster.SuperposeScoreType_RMSD
r"""Root mean square deviation"""
SuperposeScoreType_Tanimoto = _oecluster.SuperposeScoreType_Tanimoto
r"""Tanimoto coefficient [0,1]"""
SuperposeScoreType_PatchScore = _oecluster.SuperposeScoreType_PatchScore
r"""SiteHopper patch score [0,4]"""
class SuperposeOptions(object):
    r"""Configuration options for protein superposition."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    method = property(_oecluster.SuperposeOptions_method_get, _oecluster.SuperposeOptions_method_set)
    score_type = property(_oecluster.SuperposeOptions_score_type_get, _oecluster.SuperposeOptions_score_type_set)
    similarity = property(_oecluster.SuperposeOptions_similarity_get, _oecluster.SuperposeOptions_similarity_set)
    predicate = property(_oecluster.SuperposeOptions_predicate_get, _oecluster.SuperposeOptions_predicate_set, doc=r"""oeselect expression for both ref and fit""")
    ref_predicate = property(_oecluster.SuperposeOptions_ref_predicate_get, _oecluster.SuperposeOptions_ref_predicate_set, doc=r"""Override predicate for ref""")
    fit_predicate = property(_oecluster.SuperposeOptions_fit_predicate_get, _oecluster.SuperposeOptions_fit_predicate_set, doc=r"""Override predicate for fit""")

    def __init__(self):
        _oecluster.SuperposeOptions_swiginit(self, _oecluster.new_SuperposeOptions())
    __swig_destroy__ = _oecluster.delete_SuperposeOptions

# Register SuperposeOptions in _oecluster:
_oecluster.SuperposeOptions_swigregister(SuperposeOptions)
class SuperposeComparison(PairwiseComparison):
    r"""
    Protein superposition pairwise comparison using OESpruce OESuperpose.

    Supports multiple superposition methods (GlobalCarbonAlpha, Global, DDM,
    Weighted, SSE, SiteHopper) with configurable score types and atom predicates
    via oeselect expressions.

    Score semantics per method:
    - RMSD group (Global, GlobalCarbonAlpha, DDM, Weighted): raw RMSD
    - Tanimoto group (SSE): 1.0 - tanimoto (distance), raw tanimoto (similarity)
    - PatchScore group (SiteHopper): 4.0 - patch_score (distance), raw (similarity)

    Each Clone() creates a new thread-local OESuperpose instance.
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""
        *Overload 1:*

        Construct from design units.

        :param dus: Shared pointers to design units.
        :param opts: Superposition options.

        |

        *Overload 2:*

        Construct from molecules directly.

        Molecules are copied internally.

        :param mols: Pointers to molecules with 3D coordinates.
        :param opts: Superposition options.

        |

        *Overload 3:*

        Construct from molecules directly.

        Molecules are copied internally.

        :param mols: Pointers to molecules with 3D coordinates.
        :param opts: Superposition options.
        """
        _oecluster.SuperposeComparison_swiginit(self, _oecluster.new_SuperposeComparison(*args))
    __swig_destroy__ = _oecluster.delete_SuperposeComparison

    def Compare(self, i, j):
        return _oecluster.SuperposeComparison_Compare(self, i, j)

    def Size(self):
        return _oecluster.SuperposeComparison_Size(self)

    def ComparisonName(self):
        return _oecluster.SuperposeComparison_ComparisonName(self)

# Register SuperposeComparison in _oecluster:
_oecluster.SuperposeComparison_swigregister(SuperposeComparison)
class ClusteringResult(object):
    r"""
    Shared clustering result with integer labels and grouped members.

    Labels use -1 for noise. Non-negative labels identify clusters. Results are
    immutable: construct with labels and members, then read via const getters.
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _oecluster.ClusteringResult_swiginit(self, _oecluster.new_ClusteringResult(*args))
    __swig_destroy__ = _oecluster.delete_ClusteringResult

    def Labels(self):
        r"""Per-item labels; -1 marks noise."""
        return _oecluster.ClusteringResult_Labels(self)

    def Members(self):
        r"""Cluster member-index lists."""
        return _oecluster.ClusteringResult_Members(self)

    def NumClusters(self):
        r"""Number of clusters."""
        return _oecluster.ClusteringResult_NumClusters(self)

    def NumItems(self):
        r"""Number of items (length of the labels vector)."""
        return _oecluster.ClusteringResult_NumItems(self)

# Register ClusteringResult in _oecluster:
_oecluster.ClusteringResult_swigregister(ClusteringResult)
cvar = _oecluster.cvar
NOISE_LABEL = cvar.NOISE_LABEL


def labels_to_clusters(labels):
    r"""
    Convert cluster labels into cluster member lists.

    :param labels: Per-item labels, where negative values are ignored as noise.
    :returns: Clusters ordered by non-negative label, preserving item order.
    """
    return _oecluster.labels_to_clusters(labels)
class ButinaOptions(object):
    r"""Options for Butina clustering."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    distance_threshold = property(_oecluster.ButinaOptions_distance_threshold_get, _oecluster.ButinaOptions_distance_threshold_set)
    reordering = property(_oecluster.ButinaOptions_reordering_get, _oecluster.ButinaOptions_reordering_set)
    num_threads = property(_oecluster.ButinaOptions_num_threads_get, _oecluster.ButinaOptions_num_threads_set)
    chunk_size = property(_oecluster.ButinaOptions_chunk_size_get, _oecluster.ButinaOptions_chunk_size_set)

    def __init__(self):
        _oecluster.ButinaOptions_swiginit(self, _oecluster.new_ButinaOptions())
    __swig_destroy__ = _oecluster.delete_ButinaOptions

# Register ButinaOptions in _oecluster:
_oecluster.ButinaOptions_swigregister(ButinaOptions)
class ButinaResult(ClusteringResult):
    r"""
    Butina clustering result. Carries only labels and members; the first
        member of each cluster is the highest-neighborhood representative.
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _oecluster.ButinaResult_swiginit(self, _oecluster.new_ButinaResult(*args))
    __swig_destroy__ = _oecluster.delete_ButinaResult

# Register ButinaResult in _oecluster:
_oecluster.ButinaResult_swigregister(ButinaResult)

def butina_cluster(storage, options):
    r"""
    Cluster a precomputed distance matrix with the Butina algorithm.

    :param storage: Pairwise distance storage.
    :param options: Butina clustering options.
    :returns: ButinaResult whose clusters are ordered with the
        highest-neighborhood representative first, and whose per-item labels
        equal each member's cluster position.
    """
    return _oecluster.butina_cluster(storage, options)
RepresentativeMethod_Medoid = _oecluster.RepresentativeMethod_Medoid
r"""Minimize mean in-cluster distance."""
RepresentativeMethod_Minimax = _oecluster.RepresentativeMethod_Minimax
r"""Minimize maximum in-cluster distance."""
RepresentativeMethod_HighestNeighborhood = _oecluster.RepresentativeMethod_HighestNeighborhood
r"""Maximize threshold-neighbor fraction."""
RepresentativeMethod_WeightedMedoid = _oecluster.RepresentativeMethod_WeightedMedoid
r"""Combine centrality with penalty and priority metadata."""
RepresentativeSelection_Score = _oecluster.RepresentativeSelection_Score
r"""Return the top k representatives by score."""
RepresentativeSelection_Diversity = _oecluster.RepresentativeSelection_Diversity
r"""Greedily spread representatives across the cluster."""
class RepresentativeWeights(object):
    r"""Weights for weighted-medoid scoring."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    alpha = property(_oecluster.RepresentativeWeights_alpha_get, _oecluster.RepresentativeWeights_alpha_set)
    beta = property(_oecluster.RepresentativeWeights_beta_get, _oecluster.RepresentativeWeights_beta_set)
    gamma = property(_oecluster.RepresentativeWeights_gamma_get, _oecluster.RepresentativeWeights_gamma_set)

    def __init__(self):
        _oecluster.RepresentativeWeights_swiginit(self, _oecluster.new_RepresentativeWeights())
    __swig_destroy__ = _oecluster.delete_RepresentativeWeights

# Register RepresentativeWeights in _oecluster:
_oecluster.RepresentativeWeights_swigregister(RepresentativeWeights)
class RepresentativeMetrics(object):
    r"""Quality metrics for one representative member."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    mean_distance_to_cluster = property(_oecluster.RepresentativeMetrics_mean_distance_to_cluster_get, _oecluster.RepresentativeMetrics_mean_distance_to_cluster_set)
    max_distance_to_cluster = property(_oecluster.RepresentativeMetrics_max_distance_to_cluster_get, _oecluster.RepresentativeMetrics_max_distance_to_cluster_set)
    median_distance_to_cluster = property(_oecluster.RepresentativeMetrics_median_distance_to_cluster_get, _oecluster.RepresentativeMetrics_median_distance_to_cluster_set)
    neighbor_fraction_at_threshold = property(_oecluster.RepresentativeMetrics_neighbor_fraction_at_threshold_get, _oecluster.RepresentativeMetrics_neighbor_fraction_at_threshold_set)
    nearest_external_distance = property(_oecluster.RepresentativeMetrics_nearest_external_distance_get, _oecluster.RepresentativeMetrics_nearest_external_distance_set)
    cluster_radius = property(_oecluster.RepresentativeMetrics_cluster_radius_get, _oecluster.RepresentativeMetrics_cluster_radius_set)
    cluster_diameter = property(_oecluster.RepresentativeMetrics_cluster_diameter_get, _oecluster.RepresentativeMetrics_cluster_diameter_set)
    silhouette_like_score = property(_oecluster.RepresentativeMetrics_silhouette_like_score_get, _oecluster.RepresentativeMetrics_silhouette_like_score_set)
    scaffold_purity = property(_oecluster.RepresentativeMetrics_scaffold_purity_get, _oecluster.RepresentativeMetrics_scaffold_purity_set)
    representative_rank = property(_oecluster.RepresentativeMetrics_representative_rank_get, _oecluster.RepresentativeMetrics_representative_rank_set)

    def __init__(self):
        _oecluster.RepresentativeMetrics_swiginit(self, _oecluster.new_RepresentativeMetrics())
    __swig_destroy__ = _oecluster.delete_RepresentativeMetrics

# Register RepresentativeMetrics in _oecluster:
_oecluster.RepresentativeMetrics_swigregister(RepresentativeMetrics)
class ClusterRepresentative(object):
    r"""A scored representative member and its quality metrics."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    member = property(_oecluster.ClusterRepresentative_member_get, _oecluster.ClusterRepresentative_member_set)
    score = property(_oecluster.ClusterRepresentative_score_get, _oecluster.ClusterRepresentative_score_set)
    metrics = property(_oecluster.ClusterRepresentative_metrics_get, _oecluster.ClusterRepresentative_metrics_set)

    def __init__(self):
        _oecluster.ClusterRepresentative_swiginit(self, _oecluster.new_ClusterRepresentative())
    __swig_destroy__ = _oecluster.delete_ClusterRepresentative

# Register ClusterRepresentative in _oecluster:
_oecluster.ClusterRepresentative_swigregister(ClusterRepresentative)
class RepresentativeOptions(object):
    r"""Options for ranking and selecting representative members."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    method = property(_oecluster.RepresentativeOptions_method_get, _oecluster.RepresentativeOptions_method_set)
    selection = property(_oecluster.RepresentativeOptions_selection_get, _oecluster.RepresentativeOptions_selection_set)
    neighbor_threshold = property(_oecluster.RepresentativeOptions_neighbor_threshold_get, _oecluster.RepresentativeOptions_neighbor_threshold_set)
    weights = property(_oecluster.RepresentativeOptions_weights_get, _oecluster.RepresentativeOptions_weights_set)
    liability_penalties = property(_oecluster.RepresentativeOptions_liability_penalties_get, _oecluster.RepresentativeOptions_liability_penalties_set)
    priority_scores = property(_oecluster.RepresentativeOptions_priority_scores_get, _oecluster.RepresentativeOptions_priority_scores_set)
    scaffold_labels = property(_oecluster.RepresentativeOptions_scaffold_labels_get, _oecluster.RepresentativeOptions_scaffold_labels_set)

    def __init__(self):
        _oecluster.RepresentativeOptions_swiginit(self, _oecluster.new_RepresentativeOptions())
    __swig_destroy__ = _oecluster.delete_RepresentativeOptions

# Register RepresentativeOptions in _oecluster:
_oecluster.RepresentativeOptions_swigregister(RepresentativeOptions)

def rank_representatives(*args):
    r"""
    Rank every member of a cluster as a possible representative.

    :param cluster: Cluster member indices.
    :param storage: Pairwise distance storage used for scoring and metrics.
    :param options: Representative scoring options.
    :returns: Representatives ordered from best to worst under the selected method.
    :raises std::invalid_argument: If inputs are invalid or sparse distances are incomplete.
    :raises std::out_of_range: If a cluster member is outside the storage range.
    """
    return _oecluster.rank_representatives(*args)

def select_representatives(*args):
    r"""
    Select up to k representatives from a cluster.

    :param cluster: Cluster member indices.
    :param storage: Pairwise distance storage used for scoring and metrics.
    :param k: Maximum number of representatives to return.
    :param options: Representative scoring and selection options.
    :returns: Selected representatives in selection order.
    """
    return _oecluster.select_representatives(*args)

def cluster_representative(*args):
    r"""
    *Overload 1:*

    Select the best representative member index from a cluster.

    :param cluster: Cluster member indices.
    :param storage: Pairwise distance storage used for scoring.
    :param options: Representative scoring options.
    :returns: Member index selected as the cluster representative.

    |

    *Overload 2:*

    Select the best representative member index with a scoring method.

    :param cluster: Cluster member indices.
    :param storage: Pairwise distance storage used for scoring.
    :param method: Representative scoring method.
    :returns: Member index selected as the cluster representative.
    """
    return _oecluster.cluster_representative(*args)
class ClusterRepresentativeVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _oecluster.ClusterRepresentativeVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _oecluster.ClusterRepresentativeVector___nonzero__(self)

    def __bool__(self):
        return _oecluster.ClusterRepresentativeVector___bool__(self)

    def __len__(self):
        return _oecluster.ClusterRepresentativeVector___len__(self)

    def __getslice__(self, i, j):
        return _oecluster.ClusterRepresentativeVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _oecluster.ClusterRepresentativeVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _oecluster.ClusterRepresentativeVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _oecluster.ClusterRepresentativeVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _oecluster.ClusterRepresentativeVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _oecluster.ClusterRepresentativeVector___setitem__(self, *args)

    def pop(self):
        return _oecluster.ClusterRepresentativeVector_pop(self)

    def append(self, x):
        return _oecluster.ClusterRepresentativeVector_append(self, x)

    def empty(self):
        return _oecluster.ClusterRepresentativeVector_empty(self)

    def size(self):
        return _oecluster.ClusterRepresentativeVector_size(self)

    def swap(self, v):
        return _oecluster.ClusterRepresentativeVector_swap(self, v)

    def begin(self):
        return _oecluster.ClusterRepresentativeVector_begin(self)

    def end(self):
        return _oecluster.ClusterRepresentativeVector_end(self)

    def rbegin(self):
        return _oecluster.ClusterRepresentativeVector_rbegin(self)

    def rend(self):
        return _oecluster.ClusterRepresentativeVector_rend(self)

    def clear(self):
        return _oecluster.ClusterRepresentativeVector_clear(self)

    def get_allocator(self):
        return _oecluster.ClusterRepresentativeVector_get_allocator(self)

    def pop_back(self):
        return _oecluster.ClusterRepresentativeVector_pop_back(self)

    def erase(self, *args):
        return _oecluster.ClusterRepresentativeVector_erase(self, *args)

    def __init__(self, *args):
        _oecluster.ClusterRepresentativeVector_swiginit(self, _oecluster.new_ClusterRepresentativeVector(*args))

    def push_back(self, x):
        return _oecluster.ClusterRepresentativeVector_push_back(self, x)

    def front(self):
        return _oecluster.ClusterRepresentativeVector_front(self)

    def back(self):
        return _oecluster.ClusterRepresentativeVector_back(self)

    def assign(self, n, x):
        return _oecluster.ClusterRepresentativeVector_assign(self, n, x)

    def resize(self, *args):
        return _oecluster.ClusterRepresentativeVector_resize(self, *args)

    def insert(self, *args):
        return _oecluster.ClusterRepresentativeVector_insert(self, *args)

    def reserve(self, n):
        return _oecluster.ClusterRepresentativeVector_reserve(self, n)

    def capacity(self):
        return _oecluster.ClusterRepresentativeVector_capacity(self)
    __swig_destroy__ = _oecluster.delete_ClusterRepresentativeVector

# Register ClusterRepresentativeVector in _oecluster:
_oecluster.ClusterRepresentativeVector_swigregister(ClusterRepresentativeVector)
class DBSCANOptions(object):
    r"""Options for DBSCAN clustering."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    eps = property(_oecluster.DBSCANOptions_eps_get, _oecluster.DBSCANOptions_eps_set)
    min_samples = property(_oecluster.DBSCANOptions_min_samples_get, _oecluster.DBSCANOptions_min_samples_set)
    num_threads = property(_oecluster.DBSCANOptions_num_threads_get, _oecluster.DBSCANOptions_num_threads_set)
    chunk_size = property(_oecluster.DBSCANOptions_chunk_size_get, _oecluster.DBSCANOptions_chunk_size_set)

    def __init__(self):
        _oecluster.DBSCANOptions_swiginit(self, _oecluster.new_DBSCANOptions())
    __swig_destroy__ = _oecluster.delete_DBSCANOptions

# Register DBSCANOptions in _oecluster:
_oecluster.DBSCANOptions_swigregister(DBSCANOptions)
class DBSCANResult(ClusteringResult):
    r"""DBSCAN result with labels, clusters, and core sample indices."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _oecluster.DBSCANResult_swiginit(self, _oecluster.new_DBSCANResult(*args))

    def CoreSampleIndices(self):
        r"""Indices of core samples."""
        return _oecluster.DBSCANResult_CoreSampleIndices(self)
    __swig_destroy__ = _oecluster.delete_DBSCANResult

# Register DBSCANResult in _oecluster:
_oecluster.DBSCANResult_swigregister(DBSCANResult)

def dbscan_cluster(storage, options):
    r"""
    Cluster a precomputed distance matrix with DBSCAN.

    :param storage: Pairwise distance storage.
    :param options: DBSCAN clustering options.
    :returns: Labels, clusters, and core sample indices.
    :raises std::invalid_argument: If options are invalid or sparse storage is incomplete.
    """
    return _oecluster.dbscan_cluster(storage, options)
HDBSCANClusterSelectionMethod_EOM = _oecluster.HDBSCANClusterSelectionMethod_EOM
HDBSCANClusterSelectionMethod_Leaf = _oecluster.HDBSCANClusterSelectionMethod_Leaf
class HDBSCANOptions(object):
    r"""Options for HDBSCAN clustering."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    min_cluster_size = property(_oecluster.HDBSCANOptions_min_cluster_size_get, _oecluster.HDBSCANOptions_min_cluster_size_set)
    min_samples = property(_oecluster.HDBSCANOptions_min_samples_get, _oecluster.HDBSCANOptions_min_samples_set)
    cluster_selection_epsilon = property(_oecluster.HDBSCANOptions_cluster_selection_epsilon_get, _oecluster.HDBSCANOptions_cluster_selection_epsilon_set)
    max_cluster_size = property(_oecluster.HDBSCANOptions_max_cluster_size_get, _oecluster.HDBSCANOptions_max_cluster_size_set)
    alpha = property(_oecluster.HDBSCANOptions_alpha_get, _oecluster.HDBSCANOptions_alpha_set)
    cluster_selection_method = property(_oecluster.HDBSCANOptions_cluster_selection_method_get, _oecluster.HDBSCANOptions_cluster_selection_method_set)
    allow_single_cluster = property(_oecluster.HDBSCANOptions_allow_single_cluster_get, _oecluster.HDBSCANOptions_allow_single_cluster_set)
    num_threads = property(_oecluster.HDBSCANOptions_num_threads_get, _oecluster.HDBSCANOptions_num_threads_set)
    chunk_size = property(_oecluster.HDBSCANOptions_chunk_size_get, _oecluster.HDBSCANOptions_chunk_size_set)

    def __init__(self):
        _oecluster.HDBSCANOptions_swiginit(self, _oecluster.new_HDBSCANOptions())
    __swig_destroy__ = _oecluster.delete_HDBSCANOptions

# Register HDBSCANOptions in _oecluster:
_oecluster.HDBSCANOptions_swigregister(HDBSCANOptions)
class HDBSCANResult(ClusteringResult):
    r"""HDBSCAN result with labels, clusters, and membership probabilities."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _oecluster.HDBSCANResult_swiginit(self, _oecluster.new_HDBSCANResult(*args))

    def Probabilities(self):
        r"""Per-item membership probabilities."""
        return _oecluster.HDBSCANResult_Probabilities(self)
    __swig_destroy__ = _oecluster.delete_HDBSCANResult

# Register HDBSCANResult in _oecluster:
_oecluster.HDBSCANResult_swigregister(HDBSCANResult)

def hdbscan_cluster(storage, options):
    r"""
    Cluster a precomputed distance matrix with HDBSCAN.

    :param storage: Complete pairwise distance storage.
    :param options: HDBSCAN clustering options.
    :returns: Labels, clusters, and probabilities.
    """
    return _oecluster.hdbscan_cluster(storage, options)

def compute_core_distances(storage, min_samples, num_threads):
    return _oecluster.compute_core_distances(storage, min_samples, num_threads)
AgglomerativeLinkageMethod_Single = _oecluster.AgglomerativeLinkageMethod_Single
AgglomerativeLinkageMethod_Complete = _oecluster.AgglomerativeLinkageMethod_Complete
AgglomerativeLinkageMethod_Average = _oecluster.AgglomerativeLinkageMethod_Average
AgglomerativeLinkageMethod_Weighted = _oecluster.AgglomerativeLinkageMethod_Weighted
class AgglomerativeOptions(object):
    r"""Options for hierarchical agglomerative clustering."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    n_clusters = property(_oecluster.AgglomerativeOptions_n_clusters_get, _oecluster.AgglomerativeOptions_n_clusters_set)
    distance_threshold = property(_oecluster.AgglomerativeOptions_distance_threshold_get, _oecluster.AgglomerativeOptions_distance_threshold_set)
    linkage = property(_oecluster.AgglomerativeOptions_linkage_get, _oecluster.AgglomerativeOptions_linkage_set)
    compute_full_tree = property(_oecluster.AgglomerativeOptions_compute_full_tree_get, _oecluster.AgglomerativeOptions_compute_full_tree_set)
    num_threads = property(_oecluster.AgglomerativeOptions_num_threads_get, _oecluster.AgglomerativeOptions_num_threads_set)
    chunk_size = property(_oecluster.AgglomerativeOptions_chunk_size_get, _oecluster.AgglomerativeOptions_chunk_size_set)

    def __init__(self):
        _oecluster.AgglomerativeOptions_swiginit(self, _oecluster.new_AgglomerativeOptions())
    __swig_destroy__ = _oecluster.delete_AgglomerativeOptions

# Register AgglomerativeOptions in _oecluster:
_oecluster.AgglomerativeOptions_swigregister(AgglomerativeOptions)
class AgglomerativeResult(ClusteringResult):
    r"""Agglomerative clustering result with labels and merge tree metadata."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _oecluster.AgglomerativeResult_swiginit(self, _oecluster.new_AgglomerativeResult(*args))

    def ChildrenLeft(self):
        r"""Left child node index per merge."""
        return _oecluster.AgglomerativeResult_ChildrenLeft(self)

    def ChildrenRight(self):
        r"""Right child node index per merge."""
        return _oecluster.AgglomerativeResult_ChildrenRight(self)

    def Distances(self):
        r"""Merge distance per merge."""
        return _oecluster.AgglomerativeResult_Distances(self)

    def ClusterSizes(self):
        r"""Merged cluster size per merge."""
        return _oecluster.AgglomerativeResult_ClusterSizes(self)
    __swig_destroy__ = _oecluster.delete_AgglomerativeResult

# Register AgglomerativeResult in _oecluster:
_oecluster.AgglomerativeResult_swigregister(AgglomerativeResult)

def agglomerative_cluster(storage, options):
    r"""
    Cluster a complete precomputed distance matrix with agglomerative clustering.

    :param storage: Complete pairwise distance storage.
    :param options: Agglomerative clustering options.
    :returns: Labels, clusters, and merge tree metadata.
    :raises std::invalid_argument: If options are invalid or storage is incomplete.
    """
    return _oecluster.agglomerative_cluster(storage, options)
BitBirchMergeCriterion_Radius = _oecluster.BitBirchMergeCriterion_Radius
BitBirchMergeCriterion_Diameter = _oecluster.BitBirchMergeCriterion_Diameter
BitBirchMergeCriterion_Tolerance = _oecluster.BitBirchMergeCriterion_Tolerance
BitBirchMergeCriterion_ToleranceTough = _oecluster.BitBirchMergeCriterion_ToleranceTough
BitBirchMode_StrictParity = _oecluster.BitBirchMode_StrictParity
BitBirchMode_Fast = _oecluster.BitBirchMode_Fast
class BitBirchOptions(object):
    r"""Options for one-pass BitBirch clustering."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    threshold = property(_oecluster.BitBirchOptions_threshold_get, _oecluster.BitBirchOptions_threshold_set)
    branching_factor = property(_oecluster.BitBirchOptions_branching_factor_get, _oecluster.BitBirchOptions_branching_factor_set)
    merge_criterion = property(_oecluster.BitBirchOptions_merge_criterion_get, _oecluster.BitBirchOptions_merge_criterion_set)
    tolerance = property(_oecluster.BitBirchOptions_tolerance_get, _oecluster.BitBirchOptions_tolerance_set)
    singly = property(_oecluster.BitBirchOptions_singly_get, _oecluster.BitBirchOptions_singly_set)
    mode = property(_oecluster.BitBirchOptions_mode_get, _oecluster.BitBirchOptions_mode_set)
    num_threads = property(_oecluster.BitBirchOptions_num_threads_get, _oecluster.BitBirchOptions_num_threads_set)

    def __init__(self):
        _oecluster.BitBirchOptions_swiginit(self, _oecluster.new_BitBirchOptions())
    __swig_destroy__ = _oecluster.delete_BitBirchOptions

# Register BitBirchOptions in _oecluster:
_oecluster.BitBirchOptions_swigregister(BitBirchOptions)
class BitBirchReclusteringOptions(object):
    r"""Options for two-stage BitBirch reclustering."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    initial_threshold = property(_oecluster.BitBirchReclusteringOptions_initial_threshold_get, _oecluster.BitBirchReclusteringOptions_initial_threshold_set)
    second_threshold = property(_oecluster.BitBirchReclusteringOptions_second_threshold_get, _oecluster.BitBirchReclusteringOptions_second_threshold_set)
    second_tolerance = property(_oecluster.BitBirchReclusteringOptions_second_tolerance_get, _oecluster.BitBirchReclusteringOptions_second_tolerance_set)
    branching_factor = property(_oecluster.BitBirchReclusteringOptions_branching_factor_get, _oecluster.BitBirchReclusteringOptions_branching_factor_set)
    mode = property(_oecluster.BitBirchReclusteringOptions_mode_get, _oecluster.BitBirchReclusteringOptions_mode_set)
    num_threads = property(_oecluster.BitBirchReclusteringOptions_num_threads_get, _oecluster.BitBirchReclusteringOptions_num_threads_set)

    def __init__(self):
        _oecluster.BitBirchReclusteringOptions_swiginit(self, _oecluster.new_BitBirchReclusteringOptions())
    __swig_destroy__ = _oecluster.delete_BitBirchReclusteringOptions

# Register BitBirchReclusteringOptions in _oecluster:
_oecluster.BitBirchReclusteringOptions_swigregister(BitBirchReclusteringOptions)
class BitBirchRefinementOptions(object):
    r"""Options for refinement passes over a BitBirch fit."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    fit_options = property(_oecluster.BitBirchRefinementOptions_fit_options_get, _oecluster.BitBirchRefinementOptions_fit_options_set)
    redistribute_largest_cluster = property(_oecluster.BitBirchRefinementOptions_redistribute_largest_cluster_get, _oecluster.BitBirchRefinementOptions_redistribute_largest_cluster_set)
    reassign_top_clusters = property(_oecluster.BitBirchRefinementOptions_reassign_top_clusters_get, _oecluster.BitBirchRefinementOptions_reassign_top_clusters_set)
    num_threads = property(_oecluster.BitBirchRefinementOptions_num_threads_get, _oecluster.BitBirchRefinementOptions_num_threads_set)

    def __init__(self):
        _oecluster.BitBirchRefinementOptions_swiginit(self, _oecluster.new_BitBirchRefinementOptions())
    __swig_destroy__ = _oecluster.delete_BitBirchRefinementOptions

# Register BitBirchRefinementOptions in _oecluster:
_oecluster.BitBirchRefinementOptions_swigregister(BitBirchRefinementOptions)
class BitBirchResult(ClusteringResult):
    r"""BitBirch clustering result with labels, clusters, and centroid fingerprints."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _oecluster.BitBirchResult_swiginit(self, _oecluster.new_BitBirchResult(*args))

    def Centroids(self):
        r"""Centroid fingerprints, one per cluster."""
        return _oecluster.BitBirchResult_Centroids(self)

    def ClusterSizes(self):
        r"""Member count per cluster."""
        return _oecluster.BitBirchResult_ClusterSizes(self)
    __swig_destroy__ = _oecluster.delete_BitBirchResult

# Register BitBirchResult in _oecluster:
_oecluster.BitBirchResult_swigregister(BitBirchResult)

def bitbirch_cluster(*args):
    r"""
    Cluster dense binary OEFP fingerprints with BitBirch.

    :param fingerprints: Dense binary fingerprint batch.
    :param options: BitBirch clustering options.
    :returns: Labels, clusters, centroids, and cluster sizes.
    :raises std::invalid_argument: If options or fingerprints are invalid.
    """
    return _oecluster.bitbirch_cluster(*args)

def bitbirch_recluster(*args):
    r"""
    Cluster dense binary OEFP fingerprints with two-stage BitBirch reclustering.

    :param fingerprints: Dense binary fingerprint batch.
    :param options: Reclustering options.
    :returns: Labels, clusters, centroids, and cluster sizes.
    :raises std::invalid_argument: If options or fingerprints are invalid.
    """
    return _oecluster.bitbirch_recluster(*args)

def bitbirch_refine(*args):
    r"""
    Fit BitBirch and apply requested refinement passes.

    :param fingerprints: Dense binary fingerprint batch.
    :param options: Refinement options.
    :returns: Labels, clusters, centroids, and cluster sizes.
    :raises std::invalid_argument: If options or fingerprints are invalid.
    """
    return _oecluster.bitbirch_refine(*args)
OECLUSTER_VERSION_MAJOR = _oecluster.OECLUSTER_VERSION_MAJOR
OECLUSTER_VERSION_MINOR = _oecluster.OECLUSTER_VERSION_MINOR
OECLUSTER_VERSION_PATCH = _oecluster.OECLUSTER_VERSION_PATCH

__version__ = "3.4.0"


